NDefines.NCountry.BASE_STABILITY_WAR_FACTOR = -0.2			-- Default stability war factor
NDefines.NCountry.BASE_STABILITY_PARTY_POPULARITY_FACTOR = 0.2	-- Default stability rulling party popularity factor
NDefines.NCountry.MIN_STABILITY = 0
NDefines.NCountry.MAX_STABILITY = 2
NDefines.NCountry.MIN_WAR_SUPPORT = -1
NDefines.NCountry.MAX_WAR_SUPPORT = 1
NDefines.NCountryDAYS_OF_WAR_BEFORE_SURRENDER = 0
NDefines.NProduction.CAPITAL_SHIP_MAX_NAV_FACTORIES_PER_LINE = 15
NDefines.NBuildings.MAX_SHARED_SLOTS = 50
NDefines.NDiplomacy.TENSION_CAPITULATE = 0
NDefines.NMilitary.BASE_COMBAT_WIDTH = 120
