NDefines.NProduction.EQUIPMENT_MODULE_ADD_XP_COST = 1.0;
NDefines.NProduction.EQUIPMENT_MODULE_REPLACE_XP_COST = 1.0;
NDefines.NProduction.EQUIPMENT_MODULE_CONVERT_XP_COST = 1.0;
NDefines.NProduction.EQUIPMENT_MODULE_REMOVE_XP_COST = 1.0;
