NDefines.NMilitary.PLAN_SPREAD_ATTACK_WEIGHT = 3
NDefines.NMilitary.PLAYER_ORDER_PLANNING_DECAY = 0.01
NDefines.NAI.RESERVE_TO_COMMITTED_BALANCE = 0.3
NDefines.NAI.ORG_UNIT_WEAK = 0.35
NDefines.NAI.ORG_UNIT_NORMAL = 0.65
NDefines.NAI.STR_UNIT_WEAK = 0.35
NDefines.NAI.STR_UNIT_NORMAL = 0.6